package com.example.assignment2final;

public class Constants {
    public static final String DATABASE_NAME = "MatchHistory";
    public static final String TABLE_NAME = "MATCHHISTORY";
    public static final String UID = "_id";
    public static final String WL = "WL";
    public static final String SHOTS = "Shots";
    public static final String SAVES = "Saves";
    public static final int DATABASE_VERSION = 1;

}
